# Generated by Django 2.2.1 on 2019-05-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGTP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iName', models.CharField(max_length=40)),
                ('iCost', models.CharField(max_length=20)),
                ('iDescribe', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('payAccount', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Studentstset1',
        ),
        migrations.DeleteModel(
            name='useraccounttest1',
        ),
    ]
